update to latest (v0.0.32) of natscli
cloudfoundry/cf-networking-onboarding pull request #1
Opened 2022-04-25 16:58 UTC by Houlistonm

update to latest (v0.0.32) of natscli, some jq improvements; some filters for json

2022-04-26 13:52 UTC, ameowlia requested changes
🎉 Thank you so much for opening _the very first PR on this project_. 

I can see from your changes that you are a jq super user. I am hesitant to change many of the commands you suggested. I prefer making the commands as readable and understandable as possible, even if they do lack efficiency. 

However, I think jq is a powerful tool that is useful to learn.  If you are interested, I am open to you adding another story to this track or maybe a bonus section at the bottom of some of the stories with tips on how to do things with jq.

2022-04-26 13:52 UTC, ameowlia commented on http-routes/040-route-propagation-pt-2.markdown
> + cfdot actual-lrps | jq -re .
Why do you want to add the `-re` flag here?

2022-04-26 13:52 UTC, ameowlia commented on http-routes/050-route-propagation-pt-3.markdown
> +mv nats-0.0.32-linux-amd64/nats /usr/bin
👍 This part looks good.

2022-04-26 13:52 UTC, ameowlia commented on http-routes/050-route-propagation-pt-3.markdown
> +    jq -re '[to_entries[] | select(.key | startswith("nats")) ] | from_entries' /var/vcap/jobs/route_emitter/config/route_emitter.json
I think this change sacrifices understanding for efficiency. I would rather keep the old command, which I find more readable.

2022-04-26 13:52 UTC, ameowlia commented on http-routes/050-route-propagation-pt-3.markdown
> +0. Use the nats cli to connect to nats: `nats sub "router.register" -s nats://NATS_USERNAME:NATS_PASSWORD@NATS_ADDRESS/ --tlscert <cert file from json> --tlskey <key file from json> --tlsca <ca file
1. Re changing "*.*" to "router.register"
I purposefully wanted readers to subscribe to all nats messages to see how many there are and how many things use nats. I'd be open to another step after this one that shows the reader how to subscribe to just the router messages.

2. Re adding the cert information
👍  thanks!

2022-04-26 13:52 UTC, ameowlia commented on http-routes/060-route-propagation-pt-4.markdown
> + curl -s "http://USERNAME:PASSWORD@localhost:8080/routes" | jq -re '[ to_entries[] | select(.value[].tags.app_name == "appA") ] | from_entries' # return just appA
Again I think this change sacrifices understanding for efficiency. I would rather keep the old command, which I find more readable.

Also the next step asks the user to scroll though and look at all the routes and all the information associated with them, so I don't want jq pruning out any information.

2022-04-26 13:52 UTC, ameowlia commented on http-routes/080-incoming-http-requests-pt-1.markdown
> + netstat -ntulp
👍

2022-04-26 14:07 UTC, Houlistonm commented on http-routes/040-route-propagation-pt-2.markdown
> + cfdot actual-lrps | jq -re .
Honestly, it more muscle memory, the -r to unquote, and the -e to report return codes.
Just to get people into the habit of typing the command out.

2022-04-26 14:08 UTC, Houlistonm commented on http-routes/050-route-propagation-pt-3.markdown
> +    jq -re '[to_entries[] | select(.key | startswith("nats")) ] | from_entries' /var/vcap/jobs/route_emitter/config/route_emitter.json
Just trying to sneak some jq into peoples lives. :)

2022-04-27 17:31 UTC, Houlistonm commented
/easycla

2022-04-27 17:42 UTC, Houlistonm commented
/easycla

2022-04-27 19:26 UTC, Houlistonm commented
/easycla

2022-04-28 12:41 UTC, Houlistonm commented
/easycla

2022-04-28 16:21 UTC, Houlistonm commented
/easycla

2022-04-28 16:26 UTC, Houlistonm commented
/easycla

2022-04-28 17:24 UTC, ameowlia commented on http-routes/050-route-propagation-pt-3.markdown
> +   Nats is used by multiple services, and the `router.register` messages are intermixed with other messages.  Modify the sub filter from `"*.*"` to `"router.register"` to view only router messages.
Love it!

2022-04-28 17:24 UTC, ameowlia approved these changes

2022-04-28 17:25 UTC, merged

2022-04-28 17:25 UTC, ameowlia commented
🎉  First PR merged!!! 

Thank you so much for these contributions @Houlistonm!

2022-04-29 15:27 UTC, jarias-lfx commented
/easycla