Update 020-route-propagation-pt-0.markdown
cloudfoundry/cf-networking-onboarding pull request #24
Opened 2023-05-22 10:44 UTC by bjalonmontanes

I think "there will be a space provided at the bottom of each story for your to record these values" contains a typo, where "your" should be "you"

2023-05-25 13:42 UTC, ameowlia requested changes, later dismissed
Everything looks great except one typo. Thank you for making this PR!

2023-05-25 13:42 UTC, ameowlia commented on c2c/070-dataflow-pt-3.markdown
> +When a c2c policy is created, the policy server determines if the app has aCancel changes
Can you fix this?

2023-10-17 15:59 UTC, MarcPaquette commented
Hi @bjalonmontanes, 
Are you able to resolve the comment above? We'd love to get these changed merged in.

Thanks
@MarcPaquette

2023-10-25 14:19 UTC, MarcPaquette approved these changes

2023-10-25 14:20 UTC, MarcPaquette commented on c2c/070-dataflow-pt-3.markdown
> +When a c2c policy is created, the policy server determines if the app has aCancel changes
Resolving this issue in another PR

2023-10-25 14:20 UTC, merged